### ISSUE TITLE
Master Prod disaster

### ISSUE THREAD

**Issue by lbesnard** [aodn/data-services#770]
We need to put all the commits in Master back to the production branch

can all the @aodn/emii-ops  check that their PR since the 28th of sept 2017 are ready to be merged to Prod branch ?

Mine are all good to go

**Comment by ggalibert** [comment]
???!!!
Can we have a bit more explanation?
-Context
-Why do we need to check old PRs?

**Comment by lbesnard** [comment]
@lwgordonimos could give more details. But basically, some commits were holding off the master prod merge because they weren't ready for production yet. So for the last months, all the PR's which had to go to prod had to be cherrypicked.

**Comment by lbesnard** [comment]
https://github.com/aodn/data-services/pull/769

**Comment by lwgordonimos** [comment]
1. The data-services prod merge job had not been run in Jenkins since the 28th September
1. I incorrectly cherry-picked 2 commits from master into production branch since then and now (thinking it was geoserver-config, which is the one in that odd cherry picking state right now), which prevented Jenkins being able to do the merge yesterday
1. We realised the length of time since the last merge, so before merging master->production, we need to know that everything in master SINCE the 28th Sep is OK to go into production now

**Comment by ggalibert** [comment]
OK to go for my PRs since 28th Sept.

**Comment by lbesnard** [comment]
I'm pretty sure all Bene's PRs were good to go too

**Comment by mhidas** [comment]
> I incorrectly cherry-picked 2 commits from master into production branch since then and now (thinking it was geoserver-config, which is the one in that odd cherry picking state right now)

One of those cherry-picks was mine. I did it for Bene because she wanted that change in prod, but I had some already on master that were *not* ready to go into prod. They were still being tested/demoed in RC.
That's why we need to cherry-pick here, and I don't think its any different from geoserver-config.

This is why we need https://github.com/aodn/issues/issues/95

**Comment by mhidas** [comment]
All my commits in master are ready to go to prod.

**Comment by bpasquer** [comment]
All mine too

**Comment by mhidas** [comment]
Ok, I just ran `data_services_prod_merge` and it was successful, so as of right now **production == master**.

**Comment by anguss00** [comment]
![burns](https://user-images.githubusercontent.com/5964166/32260144-2c47b67c-bf1a-11e7-8e76-bbd917f674f7.gif)
